apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  os: linux
  containers:
    - name: my_container
      image: registry.bigbrother.io/app:v1.0
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 2
          memory: "512Mi"
